development:

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default
  database: daong_dev


  <<: *default
  database: daong_test

production:
  <<: *default
  database: daong_prod
production:
